<a href="https://colab.research.google.com/github/rakshamishra54/NLP_Notebooks/blob/main/Textpreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [87]:
import pandas as pd
import numpy as np
path = "/content/drive/MyDrive/IMDB Dataset.csv"

df = pd.read_csv(path)

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [88]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

###HTML Tags

In [89]:
import re

def remove_html_tags(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r'', text)

In [90]:
text ='soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you'

In [91]:
remove_html_tags(text)

'soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you'

In [92]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'' , text)

In [93]:
text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 ='Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text3= 'Google search here www.google.com'
text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1bb to search check www.google.com'

In [94]:
remove_url(text4)

'For notebook click  to search check '

###Remove Punctuation

In [95]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [96]:
exclude =string.punctuation

In [97]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char , '')
    return text

In [98]:
text= 'string. With. Punctuation?'

In [99]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string. With. Punctuation?
9.28640365600586

In [100]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [101]:
df['review'][5]

'Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas\' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight. The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. And the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. If I had a dozen thumbs, they\'d all be "up" for this movie.'

In [102]:
remove_punc1(df['review'][5])

'Probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring It just never gets old despite my having seen it some 15 or more times in the last 25 years Paul Lukas performance brings tears to my eyes and Bette Davis in one of her very few truly sympathetic roles is a delight The kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch And the mothers slow awakening to whats happening in the world and under her own roof is believable and startling If I had a dozen thumbs theyd all be up for this movie'

In [103]:
chat_words = {
    "u": "you",
    "ur": "your",
    "urs": "yours",
    "r": "are",
    "am": "am",
    "y": "why",
    "ya": "you",
    "yr": "your",
    "luv": "love",
    "lov": "love",
    "gr8": "great",
    "b4": "before",
    "2": "to",
    "4": "for",
    "2day": "today",
    "2moro": "tomorrow",
    "tmrw": "tomorrow",
    "bday": "birthday",
    "plz": "please",
    "pls": "please",
    "thx": "thanks",
    "tnx": "thanks",
    "ty": "thank you",
    "np": "no problem",
    "msg": "message",
    "txt": "text",
    "pic": "picture",
    "ppl": "people",
    "bc": "because",
    "bcz": "because",
    "coz": "because",
    "cuz": "because",
    "abt": "about",
    "w": "with",
    "w/o": "without",
    "wanna": "want to",
    "gonna": "going to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "lemme": "let me",
    "gimme": "give me",
    "idk": "I don't know",
    "ikr": "I know right",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "brb": "be right back",
    "btw": "by the way",
    "omg": "oh my god",
    "lol": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "asap": "as soon as possible",
    "fyi": "for your information",
    "dm": "direct message",
    "irl": "in real life",
    "tbh": "to be honest",
    "idc": "I don't care",
    "jk": "just kidding",
    "nvm": "never mind",
    "thx": "thanks"
}

In [104]:
def chat_conversion(text):
    new_text = []

    for w in text.split():
        if w.lower() in chat_words:
            new_text.append(chat_words[w.lower()])
        else:
            new_text.append(w)

    return " ".join(new_text)

In [105]:
chat_conversion('IMHO he is the best')

'in my humble opinion he is the best'

In [106]:
from textblob import TextBlob

In [107]:
incorrect_text = 'ceertain conditions duriiing seveal ggernations are modifieed in the same oder '
textBlb = TextBlob(incorrect_text)
textBlb.correct().string

'certain conditions during several ggernations are modified in the same oder '

In [108]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [109]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [110]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [111]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [112]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [113]:
import re

emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"
    "\U0001F300-\U0001F5FF"
    "\U0001F680-\U0001F6FF"
    "\U0001F1E0-\U0001F1FF"
    "\U00002702-\U000027B0"
    "\U000024C2-\U0001F251"
    "]+",
    flags=re.UNICODE
)

def remove_emoji(text):
    return emoji_pattern.sub('', text)

df['review'] = df['review'].apply(remove_emoji)

In [114]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [115]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [116]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.13/dist-packages (2.16.0)

In [117]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [118]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

In [119]:
# word tokenization
sent1 = 'I am going to visit delhi'
sent1.split()

['I', 'am', 'going', 'to', 'visit', 'delhi']

In [120]:
# sentence tokenization
sent2 = 'I am going to Delhi. I will stay there for 3 days '
sent2.split('.')

['I am going to Delhi', ' I will stay there for 3 days ']

In [121]:
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [122]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

In [123]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_4169/3190589682.py:3: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+", sent3)

['I', 'am', 'going', 'to', 'delhi']

In [124]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [125]:
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [126]:
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [127]:
from nltk.tokenize import sent_tokenize

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [128]:
sent5 = 'I have a Ph.D in A.I.'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I', '.']

In [129]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [130]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

In [131]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [132]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 =nlp(sent1)

In [133]:
for token in doc4:
  print(token)

I
am
going
to
visit
delhi
!

In [134]:
for token in doc3:
  print(token)

A
5
km
ride
cost
$
10.50

In [135]:
for token in doc2:
  print(token)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

In [136]:
for token in doc1:
  print(token)

I
have
a
Ph
.
D
in
A.I.

In [137]:
from nltk.stem.porter import PorterStemmer

In [138]:
ps = PorterStemmer()
def stem_words(text):
  return" ".join([ps.stem(word) for word in text.split()])

In [139]:
sample= 'Walk Walks Walking Walked'
stem_words(sample)

'walk walk walk walk'

In [140]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [141]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

In [142]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

sentence = 'He was running and eating at the same time . He has a bad habit of swimming aftmer playing long hours in the Sun'
punctuations ="?:.,:"
sentence_words =nltk.word_tokenize(sentence)
for word in sentence_words:
  if word in punctuations:
    sentence_words.remove(word)
    sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
the                 the
same                same
time                time
He                  He
has                 have
a                   a
bad                 bad
habit               habit
of                  of
swimming            swim
aftmer              aftmer
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [143]:
df = pd.DataFrame({'text':['people watch companies' , 'companies watch companies' , 'companies write comment', 'companies write comment'], 'output' :[1,1,1,0]})

In [144]:
df

                        text  output
0     people watch companies       1
1  companies watch companies       1
2    companies write comment       1
3    companies write comment       0

In [145]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [146]:
bow = cv.fit_transform(df['text'])

In [147]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'companies': 1, 'write': 4, 'comment': 0}

In [148]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]

In [149]:
cv.transform(["companies watch and write comment of companies"]).toarray()

array([[1, 2, 0, 1, 1]])

###Bag of Words, N-grams,Bi-grams and Uni-grams

In [150]:
df = pd.DataFrame({'text':['people watch companies' , 'companies watch companies' , 'companies write comment', 'companies write comment'], 'output' :[1,1,1,0]})

In [151]:
df

                        text  output
0     people watch companies       1
1  companies watch companies       1
2    companies write comment       1
3    companies write comment       0

In [152]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [153]:
bow = cv.fit_transform(df['text'])

In [154]:
print(cv.vocabulary_)

{'people': 6, 'watch': 9, 'companies': 1, 'people watch': 7, 'watch companies': 10, 'people watch companies': 8, 'companies watch': 2, 'companies watch companies': 3, 'write': 11, 'comment': 0, 'companies write': 4, 'write comment': 12, 'companies write comment': 5}

###Tf-IDF

In [155]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.37919167, 0.72664149, 0.5728925 , 0.        ],
       [0.        , 0.7979221 , 0.        , 0.60276058, 0.        ],
       [0.64043405, 0.42389674, 0.        , 0.        , 0.64043405],
       [0.64043405, 0.42389674, 0.        , 0.        , 0.64043405]])

In [156]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.         1.91629073 1.51082562 1.51082562]
['comment' 'companies' 'people' 'watch' 'write']

###WORD2VEC

In [157]:
!pip install gensim
import gensim
from gensim.models import Word2Vec, KeyedVectors

Requirement already satisfied: gensim in /usr/local/lib/python3.13/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.5.0)

In [158]:
!pip install wget

Requirement already satisfied: wget in /usr/local/lib/python3.13/dist-packages (3.2)

In [159]:
!wget -O GoogleNews-vectors-negative300.bin.gz \
"https://huggingface.co/LoganKilpatrick/GoogleNews-vectors-negative300/resolve/main/GoogleNews-vectors-negative300.bin.gz"

--2026-10-10 04:54:58--  https://huggingface.co/LoganKilpatrick/GoogleNews-vectors-negative300/resolve/main/GoogleNews-vectors-negative300.bin.gz
Resolving huggingface.co (huggingface.co)... 18.239.50.103, 18.239.50.16, 18.239.50.80, ...
Connecting to huggingface.co (huggingface.co)|18.239.50.103|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://us.gcp.cdn.hf.co/xet-bridge-us/63b498753e02c8e7cb761fd6/cfc9eb89061e73f7973c80e2a2a76bf487edcb4f55dd4bab1b3d4bdcfef40332?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27GoogleNews-vectors-negative300.bin.gz%3B+filename%3D%22GoogleNews-vectors-negative300.bin.gz%22%3B&X-Xet-Cas-Uid=public&user_id=public&response-content-type=application%2Fgzip&xip=IhYPGUeLtKQ&Expires=1791611698&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjNiNDk4NzUzZTAyYzhlN2NiNzYxZmQ2L2NmYzllYjg5MDYxZTczZjc5NzNjODBlMmEyYTc2YmY0ODdlZGNiNGY1NWRkNGJhYjFiM2Q0YmRjZmVmNDAzMzJcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomWC1YZXQtQ2FzLVVpZD1wdWJsaWMmdXNlcl9pZD1wdWJsaWMmcmVzcG9uc2UtY29udGVudC10eXBlPSomeGlwPUloWVBHVWVMdEtRIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJFcG9jaFRpbWUiOjE3OTE2MTE2OTh9fX1dfQ__&Signature=MEUCICTbtj6AFxA1Fr4zfYqCTjFshyP6iG-HVtq4rtYOtvb3AiEAlqnyrxck2hoPWJT5Pl-jxTJjq-UMGSzmbL49KlHlHcQ_&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F&Hash-Algorithm=SHA256 [following]
--2026-10-10 04:54:58--  https://us.gcp.cdn.hf.co/xet-bridge-us/63b498753e02c8e7cb761fd6/cfc9eb89061e73f7973c80e2a2a76bf487edcb4f55dd4bab1b3d4bdcfef40332?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27GoogleNews-vectors-negative300.bin.gz%3B+filename%3D%22GoogleNews-vectors-negative300.bin.gz%22%3B&X-Xet-Cas-Uid=public&user_id=public&response-content-type=application%2Fgzip&xip=IhYPGUeLtKQ&Expires=1791611698&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjNiNDk4NzUzZTAyYzhlN2NiNzYxZmQ2L2NmYzllYjg5MDYxZTczZjc5NzNjODBlMmEyYTc2YmY0ODdlZGNiNGY1NWRkNGJhYjFiM2Q0YmRjZmVmNDAzMzJcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomWC1YZXQtQ2FzLVVpZD1wdWJsaWMmdXNlcl9pZD1wdWJsaWMmcmVzcG9uc2UtY29udGVudC10eXBlPSomeGlwPUloWVBHVWVMdEtRIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJFcG9jaFRpbWUiOjE3OTE2MTE2OTh9fX1dfQ__&Signature=MEUCICTbtj6AFxA1Fr4zfYqCTjFshyP6iG-HVtq4rtYOtvb3AiEAlqnyrxck2hoPWJT5Pl-jxTJjq-UMGSzmbL49KlHlHcQ_&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F&Hash-Algorithm=SHA256
Resolving us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)... 34.117.89.69
Connecting to us.gcp.cdn.hf.co (us.gcp.cdn.hf.co)|34.117.89.69|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/gzip]
Saving to: ‘GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G   161MB/s    in 16s

2026-10-10 04:55:14 (96.8 MB/s) - ‘GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]

In [160]:
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz',binary=True,limit=500000)

In [161]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -5.59082031e-02,  7.61718750e-02, -4.14062500e-01,
       -3.65234375e-01, -3.35937500e-01, -1.54296875e-01, -2.39257812e-01,
       -3.73046875e-01,  2.27355957e-03, -3.51562500e-01,  8.64257812e-02,
        1.26953125e-01,  2.21679688e-01, -9.86328125e-02,  1.08886719e-01,
        3.65234375e-01, -5.66406250e-02,  5.66406250e-02, -1.09375000e-01,
       -1.66992188e-01, -4.54101562e-02, -2.00195312e-01, -1.22558594e-01,
        1.31835938e-01, -1.31835938e-01,  1.03027344e-01, -3.41796875e-01,
       -1.57226562e-01,  2.04101562e-01,  4.39453125e-02,  2.44140625e-01,
       -3.19824219e-02,  3.20312500e-01, -4.41894531e-02,  1.08398438e-01,
       -4.98046875e-02, -9.52148438e-03,  2.46093750e-01, -5.59082031e-02,
        4.07714844e-02, -1.78222656e-02, -2.95410156e-02,  1.65039062e-01,
        5.03906250e-01, -2.81250000e-01,  9.81445312e-02,  1.80664062e-02,
       -1.83593750e-01,  2.53906250e-01,  2.25585938e-01,  1.63574219e-02,
        1.81640625e-01,  1.38671875e-01,  3.33984375e-01,  1.39648438e-01,
        1.45874023e-02, -2.89306641e-02, -8.39843750e-02,  1.50390625e-01,
        1.67968750e-01,  2.28515625e-01,  3.59375000e-01,  1.22558594e-01,
       -3.28125000e-01, -1.56250000e-01,  2.77343750e-01,  1.77001953e-02,
       -1.46484375e-01, -4.51660156e-03, -4.46777344e-02,  1.75781250e-01,
       -3.75000000e-01,  1.16699219e-01, -1.39648438e-01,  2.55859375e-01,
       -1.96289062e-01, -2.57568359e-02, -5.41992188e-02, -2.51464844e-02,
       -1.93359375e-01, -3.17382812e-02, -8.74023438e-02, -1.32812500e-01,
       -2.12402344e-02,  4.33593750e-01, -5.20019531e-02,  3.46679688e-02,
        8.00781250e-02,  3.41796875e-02,  1.99218750e-01, -2.39257812e-02,
       -2.37304688e-01,  1.93359375e-01,  7.32421875e-02, -2.87109375e-01,
        1.25000000e-01,  8.44726562e-02,  1.30859375e-01, -2.19726562e-01,
       -1.61132812e-01, -2.63671875e-01, -5.46875000e-01, -2.96875000e-01,
        3.44238281e-02, -2.87109375e-01, -1.93359375e-01, -1.61132812e-01,
       -3.84765625e-01, -2.14843750e-01, -6.22558594e-03, -1.27929688e-01,
       -1.00097656e-01, -6.21093750e-01,  3.78906250e-01, -4.58984375e-01,
        1.44531250e-01, -9.13085938e-02, -3.08593750e-01,  2.23632812e-01,
        7.86132812e-02, -2.16796875e-01,  8.78906250e-02, -1.66992188e-01,
        1.14746094e-02, -2.53906250e-01, -6.25000000e-02,  6.04248047e-03,
        1.56250000e-01,  4.37500000e-01, -2.23632812e-01, -2.32421875e-01,
        2.75390625e-01,  2.39257812e-01,  4.49218750e-02, -7.51953125e-02,
        5.74218750e-01, -2.61230469e-02, -1.21582031e-01,  2.44140625e-01,
       -3.37890625e-01,  8.59375000e-02, -7.71484375e-02,  4.85839844e-02,
        1.43554688e-01,  4.25781250e-01, -4.29687500e-02, -1.08398438e-01,
        1.19628906e-01, -1.91406250e-01, -2.12890625e-01, -2.87109375e-01,
       -1.14746094e-01, -2.04101562e-01, -2.06298828e-02, -2.53906250e-01,
        8.25195312e-02, -3.97949219e-02, -1.57226562e-01,  1.34765625e-01,
        2.08007812e-01, -1.78710938e-01, -2.00195312e-02, -8.34960938e-02,
       -1.20605469e-01,  4.29687500e-02, -1.94335938e-01, -1.32812500e-01,
       -2.17285156e-02, -2.35351562e-01, -3.63281250e-01,  1.51367188e-01,
        9.32617188e-02,  1.63085938e-01,  1.02050781e-01, -4.27734375e-01,
        2.83203125e-01,  2.74658203e-04, -3.20312500e-01,  1.68457031e-02,
        4.06250000e-01, -5.24902344e-02,  7.91015625e-02, -1.41601562e-01,
        5.27343750e-01, -1.26953125e-01,  4.74609375e-01, -6.64062500e-02,
        3.41796875e-01, -1.78710938e-01,  3.69140625e-01, -2.05078125e-01,
        5.82885742e-03, -1.84570312e-01, -8.88671875e-02, -1.81640625e-01,
       -4.80957031e-02,  4.39453125e-01,  2.12890625e-01, -3.07617188e-02,
        9.32617188e-02,  2.40234375e-01,  2.39257812e-01,  2.51953125e-01,
       -1.98974609e-02,  1.24511719e-01, -4.73632812e-02, -2.13623047e-02,
        3.12500000e-02,  3.05175781e-02,  2.79296875e-01,  9.08203125e-02,
       -2.02148438e-01, -2.19726562e-02, -2.63671875e-01,  8.78906250e-02,
       -1.07421875e-01, -2.49023438e-01, -1.22070312e-02,  1.73828125e-01,
       -9.91210938e-02,  7.27539062e-02,  2.59765625e-01, -4.60937500e-01,
        3.59375000e-01, -2.25585938e-01,  1.87988281e-02, -2.19726562e-01,
       -2.08984375e-01, -1.51367188e-01,  8.64257812e-02,  1.11694336e-02,
        6.93359375e-02, -2.99072266e-02,  1.43554688e-01,  1.89453125e-01,
       -1.32812500e-01,  4.72656250e-01, -1.40625000e-01, -2.52685547e-02,
        1.91406250e-01, -2.63671875e-01, -1.39648438e-01,  1.09375000e-01,
        1.97753906e-02,  2.49023438e-01, -1.42578125e-01,  4.15039062e-02],
      dtype=float32)

In [162]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116),
 ('guy', 0.5420035123825073)]

In [163]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [164]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162722110748291),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('TwitterTwitter', 0.6085205674171448)]

In [165]:
model.similarity('man','woman')

np.float32(0.76640123)

In [166]:
model.similarity('man' , 'PHP')

np.float32(-0.032995153)

In [167]:
model.doesnt_match(['PHP','java','monkey'])

'monkey'

In [168]:
vec =model['king'] - model['man'] + model['woman']
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

In [169]:
print(df.columns)

Index(['text', 'output'], dtype='object')